@echo off
echo Starting DBT Application...

echo Starting Socket Server...
start "Socket Server" cmd /k "cd /d D:\project1\DBT_Application && node socket-server.js"

echo Starting Backend Server...
start "Backend Server" cmd /k "cd /d D:\project1\DBT_Application\project_backend && mvnw spring-boot:run"

echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd /d D:\project1\DBT_Application\project && npm run dev"

echo All servers are starting...
echo Check the opened terminal windows for status.
pause